flasquelistan/views/admin.py
import datetime

import flask
import flask_babel
import flask_login
import sqlalchemy as sqla
from flask import abort, current_app
from flask_babel import gettext as _
from flask_babel import lazy_gettext as _l
from flask_login import current_user

from flasquelistan import forms, models, util
from flasquelistan.discord import DiscordClient
from flasquelistan.views import auth

mod = flask.Blueprint('strequeadmin', __name__)
mod.before_request(
    flask_login.login_required(
        auth.admin_required(lambda: None)
    )
)


@mod.route('/admin/')
def index():
    return flask.render_template('strequeadmin/index.html')


@mod.route('/admin/transactions/', methods=['GET', 'POST'])
def transactions():
    form = forms.DateRangeForm()

    if form.validate_on_submit():
        from_date = form.start.data
        to_date = form.end.data

        return flask.redirect(flask.url_for('strequeadmin.transactions',
                                            from_date=from_date,
                                            to_date=to_date))

    from_date = flask.request.args.get('from_date', None)
    to_date = flask.request.args.get('to_date', None)

    if from_date and to_date:
        try:
            from_date = datetime.date.fromisoformat(from_date)
            to_date = datetime.date.fromisoformat(to_date)
        except ValueError:
            flask.flash(_l("Ogiltigt datumintervall!"), 'error')
            from_date, to_date = None, None

    if not (from_date and to_date):
        to_date = datetime.date.today()
        from_date = to_date - datetime.timedelta(days=30)

    form.start.data = from_date
    form.end.data = to_date

    transactions = models.Transaction.query.filter(
        sqla.func.DATE(models.Transaction.timestamp) >= from_date,
        sqla.func.DATE(models.Transaction.timestamp) <= to_date,
        sqla.or_(
            # Only include UserTransaction if positive, which means the
            # transaction of the payee. Include 0 too if that somehow
            # would find its way into the database. We'll just hope we
            # don't ever have a CreditTransfer where both sides are
            # negative. That could be fixed in the db admin-interface.
            models.Transaction.type.isnot('user_transaction'),
            models.Transaction.value >= 0
        )
    ).order_by(models.Transaction.timestamp.desc())

    return flask.render_template('strequeadmin/transactions.html',
                                 transactions=transactions,
                                 form=form)


@mod.route('/admin/transactions/stats', methods=['GET', 'POST'])
def streque_stats():
    form = forms.DateRangeForm()

    if form.validate_on_submit():
        from_date = form.start.data
        to_date = form.end.data

        return flask.redirect(flask.url_for('strequeadmin.streque_stats',
                                            from_date=from_date,
                                            to_date=to_date))

    from_date = flask.request.args.get('from_date', None)
    to_date = flask.request.args.get('to_date', None)

    if from_date and to_date:
        try:
            from_date = datetime.date.fromisoformat(from_date)
            to_date = datetime.date.fromisoformat(to_date)
        except ValueError:
            flask.flash(_l("Ogiltigt datumintervall!"), 'error')
            from_date, to_date = None, None

    if not (from_date and to_date):
        to_date = datetime.date.today()
        from_date = to_date - datetime.timedelta(days=1)

    form.start.data = from_date
    form.end.data = to_date

    counts = (
        models.User.query
        .join(models.Streque, models.User.id == models.Streque.user_id)
        .with_entities(
            models.User.first_name,
            models.User.last_name,
            sqla.func.count(models.Streque.user_id).label('count')
        )
        .filter(
            sqla.func.DATE(models.Streque.timestamp) >= from_date,
            sqla.func.DATE(models.Streque.timestamp) <= to_date,
            models.Streque.voided.is_(False)
        )
        .group_by(
            models.Streque.user_id
        )
        .order_by(sqla.desc('count'))
    )

    return flask.render_template('strequeadmin/streque_stats.html',
                                 counts=counts,
                                 form=form)


@mod.route('/admin/transactions/void', methods=['POST'])
def void_transaction():
    if flask.request.is_json:
        data = flask.request.get_json()
    else:
        form = forms.VoidTransactionForm()
        data = {
            'transaction_id': form.transaction_id.data
        }

    try:
        transaction_id = data['transaction_id']
    except (KeyError, TypeError):
        flask.abort(400)

    transaction = models.Transaction.query.get(transaction_id)

    if not transaction or transaction.voided:
        flask.abort(400)

    if transaction.type == 'user_transaction':
        credit_transfer = models.CreditTransfer.query.filter(
            sqla.or_(
                # As we include potential transactions where value is 0
                # (maybe on both sides), we'll search on both sides
                # here.
                models.CreditTransfer.payer_transaction_id.is_(transaction.id),
                models.CreditTransfer.payee_transaction_id.is_(transaction.id),
            )
        ).first()
        credit_transfer.void()
    else:
        transaction.void_and_refund()

    if flask.request.is_json:
        return flask.jsonify(
            transaction_id=transaction.id,
            user_id=transaction.user.id,
            value=transaction.value,
            balance=transaction.user.balance
        )

    else:
        flask.flash(
            _("Ångrade %(type)s \"%(text)s\", "
              "%(value)s den %(date)s på %(user)s.",
              type=transaction.type,
              text=transaction.text,
              value=transaction.formatted_value,
              date=flask_babel.format_datetime(
                  transaction.timestamp,
                  "dd MMMM yyyy, HH:mm"
              ),
              user=transaction.user.full_name
              ),
            'success'
        )
        return flask.redirect(flask.url_for('strequeadmin.transactions'))


@mod.route('/admin/transactions/bulk', methods=['GET', 'POST'])
def bulk_transactions():
    if flask.request.args.get('active') == 'True':
        only_active = True
    else:
        only_active = False
    form = forms.BulkTransactionFormFactory(only_active=only_active)

    if form.validate_on_submit():
        transactions = []

        for form_field in form:
            if form_field.name == 'csrf_token':
                continue

            if form_field.value.data:
                user = models.User.query.get(form_field.user_id.data)
                if user:
                    transactions.append({
                        'user_id': user.id,
                        'user_name': user.full_name,
                        'value': int(form_field.value.data * 100),
                        'text': form_field.text.data or _l('Admintransaktion')
                    })

        if transactions:
            return flask.render_template(
                'strequeadmin/confirm_bulk_transactions.html',
                transactions=transactions)
        else:
            flask.flash(_l("Inga transaktioner utförda. "
                        "Väl spenderade klockcykler, bra jobbat!"), 'info')

    return flask.render_template(
        'strequeadmin/bulk_transactions.html',
        form=form,
        only_active=only_active
    )


@mod.route('/admin/transactions/bulk/confirm', methods=['POST'])
def confirm_bulk_transactions():
    form = flask.request.form
    transactions = {}

    for name, value in form.items():
        if not name.startswith('user'):
            continue

        user_id, field = name.split('-')[1:]

        transactions.setdefault(user_id, {})
        if field == 'value':
            transactions[user_id][field] = int(value)
        elif field == 'text':
            transactions[user_id][field] = value
        else:
            flask.abort(400)

    for user_id, transaction_data in transactions.items():
        user = models.User.query.get(user_id)
        transaction = user.admin_transaction(
            transaction_data['value'],
            transaction_data['text'],
            by_user=current_user
        )
        transaction.create_notification()

    flask.flash(_l("Transaktionerna utfördes!"), 'success')
    return flask.redirect(flask.url_for('strequeadmin.bulk_transactions'))


@mod.route('/admin/articles/')
def articles():
    articles = (models.Article
                .query
                .order_by(
                    models.Article.is_active.desc(),
                    models.Article.weight.desc()
                )
                .all()
                )
    return flask.render_template('strequeadmin/articles.html', articles=articles)


@mod.route('/admin/articles/new', methods=['GET', 'POST'])
@mod.route('/admin/articles/edit/<int:article_id>', methods=['GET', 'POST'])
def edit_article(article_id=None):
    if article_id:
        article = models.Article.query.get_or_404(article_id)
        form = forms.EditArticleForm(obj=article)
        if not form.is_submitted():
            form.value.data = form.value.data / 100
    else:
        article = None
        form = forms.EditArticleForm()

    if form.validate_on_submit():
        if not article:
            article = models.Article()
            flash = _l("Produkt \"{}\" skapad.")
        else:
            flash = _("Produkt \"{}\" ändrad.")

        article.name = form.name.data
        article.value = int(form.value.data * 100)
        article.description = form.description.data
        article.weight = form.weight.data
        article.standardglas = form.standardglas.data
        article.is_active = form.is_active.data

        if not article_id:

flasquelistan/views/quotes.py
import flask
import flask_login
from flask_babel import lazy_gettext as _l

from flasquelistan import forms, models

mod = flask.Blueprint('quotes', __name__)
mod.before_request(flask_login.login_required(lambda: None))


@mod.route('/quotes/', methods=['GET', 'POST'])
def index():
    quotes = models.Quote.query.order_by(models.Quote.timestamp.desc(),
                                         models.Quote.id.desc()).all()

    return flask.render_template('quotes.html', quotes=quotes)


@mod.route('/quotes/new', methods=['GET', 'POST'])
def add_quote():
    form = forms.QuoteForm()
    if form.validate_on_submit():
        quote = models.Quote(text=form.text.data, who=form.who.data)
        models.db.session.add(quote)
        models.db.session.commit()
        flask.flash(_l('Citat tillagt!'), 'success')
        return flask.redirect(flask.url_for('.index'))

    return flask.render_template('add_quote.html', form=form)


@mod.route('/quotes/<int:quote_id>')
def quote(quote_id):
    quote = models.Quote.query.get_or_404(quote_id)

    return flask.render_template('quote.html', quote=quote)

flasquelistan/templates/strequeadmin/confirm_bulk_transactions.html
{% extends "strequeadmin/layout.html" %}

{% block scripts %}
<script defer src="{{ url_for('static', filename='js/common.js') }}"></script>
<script defer src="{{ url_for('static', filename='js/admin.js') }}"></script>
{% endblock %}

{% block body %}
<div class="transactions">
  <h2>{{ _("Gör transaktioner i bulk") }}</h2>
  <p>{{ _("Positivt transaktionsvärde innebär en insättning till användarens konto, negativt innebär ett uttag.") }}</p>
  <p>{{ _("Dessa transaktioner kommer genomföras, vill du fortsätta?") }}</p>
  <p>{{ _("Använd bakåt-knappen i webbläsaren istället för \"Avbryt\" ifall du vill ha kvar värdena!") }}</p>
  <form method="POST" action="{{ url_for('strequeadmin.confirm_bulk_transactions') }}">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class="table-wrap bulk-transactions">
      <table>
        <tr>
          <th>{{ _("Användare") }}</th>
          <th>{{ _("Typ") }}</th>
          <th>{{ _("Transaktionsvärde") }}</th>
          <th>{{ _("Meddelande") }}</th>
        </tr>
        {% for transaction in transactions %}
        <tr>
          <td>
            <span class="user">
              {{ transaction.user_name }}
            </span>
          </td>
          <td>
            {% if transaction.value > 0 %}
            <span class="type deposit">
              {{ _("Insättning") }}
            </span>
            {% else %}
            <span class="type withdrawal">
              {{ _("Uttag") }}
            </span>
            {% endif %}
          </td>
          <td>
            <span class="value">
              <input type="hidden" name="user-{{ transaction.user_id }}-value" value="{{ transaction.value }}"/>
              {{ format_currency(transaction.value/100, 'SEK') }}
            </span>
          </td>
          <td>
            <span class="text">
              <input type="hidden" name="user-{{ transaction.user_id }}-text" value="{{ transaction.text }}"/>
              {{ transaction.text }}
            </span>
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
    <div class="form-field">
        <button>{{ _("Skicka") }}</button> | <a href="{{ url_for('strequeadmin.bulk_transactions') }}">{{ _("Avbryt") }}</a>
    </div>
  </form>
</div>
{% endblock %}

flasquelistan/templates/strequeadmin/edit_article.html
{% extends "strequeadmin/layout.html" %}

{% from "macros.html" import form_entry %}

{% block scripts %}
<script defer src="{{ url_for("static", filename="js/confirmDialog.js") }}"></script>
<script defer src="{{ url_for("static", filename="js/calculateStandardglas.js") }}"></script>
{% endblock %}

{% block body %}
<div>
  <h2>{% if article %}{{ _("Redigera") }}{% else %}{{ _("Skapa") }}{% endif %} {{ _("produkt") }}</h2>
  <form method="POST">
    {{ form.csrf_token }}

    {{ form_entry(form.name) }}
    {{ form_entry(form.value) }}
    {{ form_entry(form.standardglas) }}
    {{ form_entry(form.description, cols=30, rows=5) }}
    {{ form_entry(form.weight) }}
    {{ form_entry(form.is_active) }}

    {% if article %}
    <div class="form-entry">
      <button class="confirm" formaction="{{ url_for('strequeadmin.remove_article', article_id=article.id) }}">{{ _("Ta bort produkt") }}</button>
    </div>
    {% endif %}

    <div class="form-entry">
      <button>{{ _("Spara") }}</button> | <a href="{{ url_for('strequeadmin.articles') }}">{{ _("Avbryt") }}</a>
    </div>
  </form>
</div>
</div>
{% endblock %}

flasquelistan/templates/strequeadmin/edit_group.html
{% extends "strequeadmin/layout.html" %}

{% from "macros.html" import form_entry %}

{% block scripts %}
<script defer src="{{ url_for("static", filename="js/confirmDialog.js") }}"></script>
{% endblock %}

{% block body %}
<div>
  <h2>{% if group %}{{ _("Redigera") }}{% else %}{{ _("Skapa") }}{% endif %} {{ _("grupp") }}</h2>
  <form method="POST">
    {{ form.csrf_token }}

    {{ form_entry(form.name) }}
    {{ form_entry(form.weight) }}
    {{ form_entry(form.active) }}
    {{ form_entry(form.discord_sync) }}

    {% if group %}
    <div class="form-entry">
      <button class="confirm" formaction="{{ url_for('strequeadmin.remove_group', group_id=group.id) }}">{{ _("Ta bort grupp") }}</button>
    </div>
    {% endif %}

    <div class="form-entry">
        <button>{{ _("Spara") }}</button> | <a href="{{ url_for('strequeadmin.show_groups') }}">{{ _("Avbryt") }}</a>
    </div>
  </form>
</div>
</div>
{% endblock %}

flasquelistan/templates/strequeadmin/edit_quote.html
{% extends "strequeadmin/layout.html" %}

{% from "macros.html" import form_entry %}

{% block scripts %}
<script defer src="{{ url_for("static", filename="js/confirmDialog.js") }}"></script>
{% endblock %}

{% block body %}
<div>
  <h2>{{ _("Redigera citat") }}</h2>
  <form method="POST">
    {{ form.csrf_token }}

    {{ form_entry(form.text, cols=30, rows=5) }}
    {{ form_entry(form.who, cols=30, rows=5) }}
    {{ form_entry(form.timestamp, placeholder='yyyy-MM-ddTHH:mm') }}

    <div class="form-entry">
      <button class="confirm" formaction="{{ url_for('strequeadmin.remove_quote', quote_id=quote.id) }}">{{ _("Ta bort citat") }}</button>
    </div>

    <div class="form-entry">
      <button>{{ _("Spara") }}</button> | <a href="{{ url_for('strequeadmin.show_quotes') }}">{{ _("Avbryt") }}</a>
    </div>
  </form>
</div>
{% endblock %}

flasquelistan/templates/strequeadmin/index.html
{% extends "strequeadmin/layout.html" %}

{% block body %}
<div class="admin-index">
  <h2>{{ _("Admin") }}</h2>
  <h3>{{ _("Användare") }}</h3>
  <ul>
    <li><a href="{{ url_for("strequeadmin.add_user") }}">{{ _("Skapa användare") }}</a></li>
    <li><a href="{{ url_for("strequeadmin.requests") }}">{{ _("Kontoförfrågningar") }}</a></li>
    <li><a href="{{ url_for("strequeadmin.show_users") }}">{{ _("Lista över användare") }}</a></li>
    <li><a href="{{ url_for("strequeadmin.show_groups") }}">{{ _("Grupper") }}</a></li>
    <li><a href="{{ url_for("strequeadmin.spam") }}">{{ _("Skicka saldopåminnelser") }}</a></li>
  </ul>
  <h3>{{ _("Transaktioner") }}</h3>
  <ul>
    <li><a href="{{ url_for("strequeadmin.transactions") }}">{{ _("Transaktionshistorik") }}</a></li>
    <li><a href="{{ url_for("strequeadmin.bulk_transactions") }}">{{ _("Gör bulktransaktioner") }}</a></li>
    <li><a href="{{ url_for("strequeadmin.streque_stats") }}">{{ _("Antal transaktioner per användare") }}</a></li>
  </ul>
  <h3>{{ _("Produkter") }}</h3>
  <ul>
    <li><a href="{{ url_for("strequeadmin.articles") }}">{{ _("Produkter") }}</a></li>
  </ul>
  <h3>{{ _("Generera en papperslista") }}</h3>
  <form action="{{ url_for("strequelistan.paperlist") }}" method="GET">
    <ul>
      <li>Endast aktiva: <input type="checkbox" name="active" value="true"></li>
      <li>Extra rader: <input type="number" name="empty" value="0"></br></li>
      <li><input type="submit" value="{{ _("Generera") }}"></li>
    </ul>
  </form>
  <h3>{{ _("Annat") }}</h3>
  <ul>
    <li><a href="{{ url_for("strequeadmin.show_quotes") }}">{{ _("Citat") }}</a></li>
    <li><a href="{{ url_for("strequeadmin.show_nicknames") }}">{{ _("Smeknamn") }}</a></li>
    <li><a href="{{ url_for("strequeadmin.stats") }}">{{ _("Statistik") }}</a></li>
    <li><a href="{{ url_for("admin.index") }}">{{ _("Databas-admin") }}</a></li>
  </ul>
</div>
{% endblock %}

flasquelistan/templates/strequeadmin/layout.html
{% extends "layout.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
{% endblock %}

flasquelistan/templates/strequeadmin/nicknames.html
{% extends "strequeadmin/layout.html" %}

{% block scripts %}
<script defer src="{{ url_for('static', filename='js/common.js') }}"></script>
<script defer src="{{ url_for('static', filename='js/admin.js') }}"></script>
<script defer src="{{ url_for("static", filename="js/confirmDialog.js") }}"></script>
{% endblock %}

{% block body %}
<div>
  <h2>{{ _("Ej granskade smeknamn") }}</h2>
  {% if pending_changes %}
  <p class="nickname-info">
    {{ _("Om det finns flera smeknamnsförslag för samma person så är det smeknamnet du
    godkänner sist som blir det aktiva smeknamnet (övriga kommer finnas kvar i
    historiken).") }}
  </p>
  <div class="table-wrap">
    <table class="quotes">
      <tr>
        <th>{{ _("Person") }}</th>
        <th>{{ _("Smeknamn") }}</th>
        <th>{{ _("Inlagt") }}</th>
        <th>{{ _("Inlagt av") }}</th>
        <th></th>
        <th></th>
      </tr>
      {% for change in pending_changes %}
      <tr>
        <td class="user">
          <span>
            <a href="{{ url_for('strequelistan.user_nicknames', user_id=change.user.id) }}">
                {{ change.user.first_name }} {{ change.user.last_name }}
            </a>
          </span>
        </td>
        <td class="nickname">
          <span>
            {{ change.nickname }}
          </span>
        </td>
        <td class="created_timestamp">
          <span>
            {{ format_datetime(change.created_timestamp, "yyyy-MM-dd, HH:mm") }}
          </span>
        </td>
        <td class="suggester">
          <span>
            {{ change.suggester.first_name }} {{ change.suggester.last_name }}
          </span>
        </td>
        <td class="approve">
          <form method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <button formaction="{{ url_for('strequeadmin.approve_pending_nickname', change_id=change.id) }}">{{ _("Godkänn") }}</button>
          </form>
        </td>
        <td class="reject">
          <form method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <button class="confirm" formaction="{{ url_for('strequeadmin.reject_pending_nickname', change_id=change.id) }}">{{ _("Neka") }}</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
  {% else %}
  {{ _("Det finns inga icke-granskade smeknamnsförslag.") }}
  {% endif %}

  <h2>{{ _("Godkända smeknamn") }}</h2>
  <p class="nickname-info">
    {{ _('Om "Godkänt av" saknas innebär det att ändringen ej krävde godkännande. Detta är
    fallet t.ex. när någon ändrat sitt eget smeknamn, ändringar gjorda av admins, och för
    gamla smeknamnsändringar. Där det finns två tider för "Skapat" betyder det att vi ej
    vet exakt när smeknamnet lades in, utan bara att det var mellan de två tiderna.') }}
  </p>
  <div class="table-wrap">
    <table class="quotes">
      <tr>
        <th>{{ _("Person") }}</th>
        <th>{{ _("Smeknamn") }}</th>
        <th>{{ _("Skapat") }}</th>
        <th>{{ _("Skapare") }}</th>
        <th>{{ _("Godkänt") }}</th>
        <th>{{ _("Godkänt av") }}</th>
      </tr>
      {% for change in approved_changes %}
      <tr>
        <td class="user">
          <span>
            <a href="{{ url_for('strequelistan.user_nicknames', user_id=change.user.id) }}">
                {{ change.user.first_name }} {{ change.user.last_name }}
            </a>
          </span>
        </td>
        <td class="nickname">
          <span>
            {{ change.nickname }}
          </span>
        </td>
        <td class="created_timestamp">
          <span>
            {#
              If we don't know the exact time a nickname was added, show an interval.
              If we do, just show the timestamp.
            #}
            {% if change.lower_bound_timestamp %}
            {{ format_datetime(change.lower_bound_timestamp, "yyyy-MM-dd, HH:mm") }} /
            {% endif %}
            {{ format_datetime(change.created_timestamp, "yyyy-MM-dd, HH:mm") }}
          </span>
        </td>
        <td class="suggester">
          <span>
            {{ change.suggester.first_name }} {{ change.suggester.last_name }}
          </span>
        </td>
        <td class="reviewed_timestamp">
          <span>
            {% if change.reviewed_timestamp %}
              {{ format_datetime(change.reviewed_timestamp, "yyyy-MM-dd, HH:mm") }}
            {% endif %}
          </span>
        </td>
        <td class="reviewer">
          <span>
            {{ change.reviewer.first_name }} {{ change.reviewer.last_name }}
          </span>
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>
{% endblock %}

flasquelistan/templates/strequeadmin/quote_reactions.html
{% extends "strequeadmin/layout.html" %}

{% block body %}
<div>
  <h2>{{ _("Citatreaktioner") }}</h2>
  <ul>
    {% for reaction in reactions %}
      <li>
        <form method="POST" action="{{ url_for('strequeadmin.remove_quote_reaction', reaction_item_id=reaction.id) }}">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
          {{ reaction.item }} - <button type="submit">{{ _("Ta bort") }}</button>
        </form>
      </li>
    {% endfor %}
    <li>
      <form method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <input name="reaction_item">
        - <button type="submit">{{ _("Lägg till") }}</button>
      </form>
    </li>
</div>
{% endblock %}

flasquelistan/templates/strequeadmin/transactions.html
{% extends "strequeadmin/layout.html" %}

{% from "macros.html" import form_entry %}

{% block scripts %}
<script defer src="{{ url_for('static', filename='js/common.js') }}"></script>
<script defer src="{{ url_for('static', filename='js/admin.js') }}"></script>
{% endblock %}

{% block body %}
<div class="transactions">
  <h2>{{ _("Transaktionshistorik") }}</h2>
  <form class="date-range-form" method="POST">
    {{ form.csrf_token }}
    {{ form_entry(form.start) }}
    {{ form_entry(form.end) }}
    <button>{{ _("Sök") }}</button>
  </form>
  {% if transactions.all() %}
  <div class="table-wrap">
    <table class="transaction-history">
      <tr>
        <th>{{ _("Användare") }}</th>
        <th>{{ _("Skapad av") }}</th>
        <th>{{ _("API-nyckel") }}</th>
        <th>{{ _("Transaktionstyp") }}</th>
        <th>{{ _("Meddelande") }}</th>
        <th>{{ _("Värde") }}</th>
        <th>{{ _("Datum") }}</th>
      </tr>
      {% for transaction in transactions %}
      <tr>
        <td class="user">
          <span>
            <a href="{{ url_for('strequelistan.show_profile', user_id=transaction.user_id) }}">
              {{ transaction.user.full_name }}
            </a>
          </span>
        </td>
        <td class="user">
          <span>
            {% if transaction.created_by %}
            <a href="{{ url_for('strequelistan.show_profile', user_id=transaction.created_by_id) }}">
              {{ transaction.created_by.full_name }}
            </a>
            {% else %}
            {{ _("Okänt") }}
            {% endif %}
          </span>
        </td>
        <td class="user">
          <span>
            {% if transaction.api_key %}
            <a href="{{ url_for('strequelistan.edit_api_key', user_id=transaction.api_key.user.id, api_key_id=transaction.api_key.id) }}">
            {% if transaction.api_key.short_name %}
            {{ transaction.api_key.short_name }}
            {% else %}
            {{ transaction.api_key.name }}
            {% endif %}
            </a>
            {% endif %}
          </span>
        </td>
        <td class="type">
          <span>
            {% if transaction.type == 'streque' %}
            {{ _("Streque") }}
            {% elif transaction.type == 'admin_transaction' %}
            {{ _("Admin") }}
            {% elif transaction.type == 'user_transaction' %}
            {{ _("Pay") }}
            {% else %}
            {{ transaction.type }}
            {% endif %}
          </span>
        </td>
        <td class="text">
          <span>
            {{ transaction.text }}
          </span>
        </td>
        <td class="value">
          <span>
            {{ transaction.formatted_value }}
          </span>
        </td>
        <td class="timestamp">
          <span>
            {{ format_datetime(transaction.timestamp, "yyyy-MM-dd HH:mm") }}
          </span>
        </td>
        <td>
          {% if not transaction.voided %}
          <form id="void-transaction-{{ transaction.id }}"
                class="transaction void-form"
                action="{{ url_for('strequeadmin.void_transaction') }}"
                method="POST">

            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input type="hidden" name="transaction_id" value="{{ transaction.id }}"/>

            <button class="transaction void-button"
                    data-transactionid="{{ transaction.id }}"
                    data-csrftoken="{{ csrf_token() }}">
              {{ _("Ångra") }}
            </button>
          </form>
          {% else %}
          {{ _("Ångrad") }}
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
  {% else %}
  <p>{{ _("Inga transaktioner funna.") }}</p>
  {% endif %}
</div>
{% endblock %}