flasquelistan/views/misc.py
import flask
import flask_login
from flasquelistan.views import auth

mod = flask.Blueprint('misc', __name__)


@mod.before_request
@flask_login.login_required
def before_request():
    """Make sure user is logged in before request.
    This function does nothing, but the decorators do.
    """
    pass


@mod.route('/mer/')
def index():
    return flask.render_template('misc.html')

flasquelistan/views/quotes.py
import flask
import flask_login
from flask_babel import lazy_gettext as _l

from flasquelistan import forms, models

mod = flask.Blueprint('quotes', __name__)
mod.before_request(flask_login.login_required(lambda: None))


@mod.route('/quotes/', methods=['GET', 'POST'])
def index():
    quotes = models.Quote.query.order_by(models.Quote.timestamp.desc(),
                                         models.Quote.id.desc()).all()

    return flask.render_template('quotes.html', quotes=quotes)


@mod.route('/quotes/new', methods=['GET', 'POST'])
def add_quote():
    form = forms.QuoteForm()
    if form.validate_on_submit():
        quote = models.Quote(text=form.text.data, who=form.who.data)
        models.db.session.add(quote)
        models.db.session.commit()
        flask.flash(_l('Citat tillagt!'), 'success')
        return flask.redirect(flask.url_for('.index'))

    return flask.render_template('add_quote.html', form=form)


@mod.route('/quotes/<int:quote_id>')
def quote(quote_id):
    quote = models.Quote.query.get_or_404(quote_id)

    return flask.render_template('quote.html', quote=quote)

flasquelistan/views/songbook.py
from flask import Blueprint, send_from_directory
from flask_login import login_required

songbook = Blueprint('songbook', __name__)

@songbook.route('/bok/')
@login_required
def index():
    return send_from_directory('songbook_dist', 'index.html')

@songbook.route('/bok/<path:path>')
@login_required
def assets(path):
    return send_from_directory('songbook_dist', path)

flasquelistan/views/strequelistan.py
import datetime
import hashlib
import os
import sys
import traceback

import flask
import flask_babel
from flask import current_app, abort, request
from flask_babel import gettext as _
from flask_babel import lazy_gettext as _l
from flask_login import current_user, login_required
from flask_uploads import UploadNotAllowed
from sqlalchemy.sql.expression import extract, func, not_
from config import ADMIN_EMAILADDR

from flasquelistan import forms, models, util
from flasquelistan.views import auth
from flasquelistan.discord import DiscordClient

mod = flask.Blueprint('strequelistan', __name__)
mod.before_request(login_required(lambda: None))


@mod.route('/')
def index():
    groups = (models.Group
              .query
              .filter(models.Group.users.any())  # Only groups with users
              .order_by(models.Group.weight.desc())
              .all()
              )

    vip = (
        models.User
        .query
        .filter(
            models.User.active.is_(True),
            models.User.balance >= 1000 * 100,
        )
        .order_by(models.User.balance.desc())
        .all()
    )

    too_old = datetime.datetime.utcnow() - datetime.timedelta(days=7)
    users_with_streques = (
        models.User
        .query
        .join(models.User.transactions)
        .filter(
            models.Transaction.type.is_('streque'),
            models.Streque.voided.is_(False),
            models.Streque.timestamp >= too_old,
            models.Streque.standardglas > 0
        )
        .all()
    )

    current_app.jinja_env.filters['is_active'] = \
        lambda l: [i for i in l if i.active]

    today = datetime.date.today()
    birthdays = (
        models.User
        .query
        .filter(
            extract('month', models.User.birthday) == today.month,
            extract('day', models.User.birthday) == today.day
        )
        .order_by(models.User.first_name)
        .all()
    )
    if birthdays:
        emojis = ['🎂', '🍰', '🧁', '✨', '🍾', '🎉', '🎈']
        md5 = hashlib.md5(today.isoformat().encode())
        i = int.from_bytes(md5.digest(), 'little') % len(emojis)
        birthday_emoji = emojis[i]
    else:
        birthday_emoji = None

    random_quote = models.Quote.query.order_by(func.random()).first()

    articles = (
        models.Article
        .query
        .filter_by(is_active=True)
        .order_by(models.Article.weight.desc())
        .all()
    )

    if util.is_discord_launched_yet():
        # If the user has not yet connected their Discord account, and they are in a group
        # connected to Discord, show a flash message.
        if (not current_user.discord_user_id and
            current_user.group and
            current_user.group.discord_role_id):
            flask.flash(
                _l('Kören har flyttat från Messenger till Discord!') +
                f' <a href="{ flask.url_for("strequelistan.discord")}">' +
                _l('Gå med i vår Discord-server här.') +
                '</a>',
                'info'
            )

    if current_app.config.get('DISPLAY_BALANCE_WARNINGS', True):
        if current_user.balance <= 0:
            flask.flash(
                _l("Det finns inga pengar på kontot. Dags att fylla på!"),
                'error'
            )
        elif current_user.balance < 10000:
            flask.flash(
                _l("Det är ont om pengar på kontot. Dags att fylla på?"),
                'warning'
            )

    notification_count = (
        models.Notification
        .query
        .filter_by(
            user_id=current_user.id,
            is_acknowledged=False
        )
        .count()
    )

    if current_user.is_admin:
        has_pending_nicknames = (models.NicknameChange.query
            .filter_by(status=models.NicknameChangeStatus.PENDING).count() > 0)
    else:
        has_pending_nicknames = False

    return flask.render_template(
        'strequelistan.html',
        groups=groups,
        quote=random_quote,
        articles=articles,
        notification_count=notification_count,
        has_pending_nicknames=has_pending_nicknames,
        users_with_streques=users_with_streques,
        birthdays=birthdays,
        birthday_emoji=birthday_emoji,
        vip=vip
    )


@mod.route('/strequa', methods=['POST'])
def add_streque():
    if flask.request.is_json:
        data = flask.request.get_json()
    else:
        form = forms.AddStrequeForm()
        data = {
            'user_id': form.user_id.data,
            'article_id': form.article_id.data
        }

    try:
        user = models.User.query.get(data['user_id'])
        article_id = int(data['article_id'])
    except (KeyError, ValueError, TypeError):
        flask.abort(400)

    article = models.Article.query.get(article_id)

    if not article:
        flask.abort(400)

    streque = user.strequa(article, current_user)

    if user != current_user:
        text = "{name} strequade en {article} på dig.".format(
            name=current_user.displayname,
            article=article.name
        )
        notification = models.Notification(
            text=text,
            user_id=user.id,
            type='streque',
            reference=str(streque.id)
        )
        models.db.session.add(notification)
        models.db.session.commit()
        util.emit_notification_event(notification)

    if flask.request.is_json:
        response = {
            'user_id': user.id,
            'value': streque.value,
        }

        if user == current_user:
            response['balance'] = user.balance

        return flask.jsonify(response)

    else:
        flask.flash(_("%(text)s-streque på %(name)s tillagt.",
                      text=streque.text, name=user.full_name),
                    'success')
        return flask.redirect(flask.url_for('strequelistan.index'))


@mod.route('/void', methods=['POST'])
def void_streque():
    if flask.request.is_json:
        data = flask.request.get_json()
    else:
        form = forms.VoidStrequeForm()
        data = {
            'streque_id': form.streque_id.data
        }

    try:
        streque_id = data['streque_id']
    except (KeyError, ValueError):
        flask.abort(400)

    streque = models.Streque.query.get(streque_id)

    if not streque or streque.too_old() or streque.voided:
        flask.abort(400)

    streque.void_and_refund()

    streque_notification = (
        models.Notification
        .query
        .filter_by(
            user_id=streque.user.id,
            type='streque',
            reference=str(streque.id),
            is_sent=False
        )
        .first()
    )
    if streque_notification:
        # Found a notification, and it has not been sent.
        # Remove it as if nothing happened! :O
        models.db.session.delete(streque_notification)
    elif streque.user_id != current_user.id:
        # The notification has been sent and potentially read, we must
        # send a new notification that the streque was voided.
        text = "{name} ångrade ett av dina {article}-streque.".format(
            name=current_user.displayname,
            article=streque.text
        )
        void_notification = models.Notification(
            text=text,
            user_id=streque.user_id,
            type='streque-void',
            reference=str(streque.id)
        )
        models.db.session.add(void_notification)
        models.db.session.commit()
        util.emit_notification_event(void_notification)

    models.db.session.commit()

    if flask.request.is_json:
        return flask.jsonify(
            streque_id=streque.id,
            user_id=streque.user.id,
            value=streque.value,
            balance=streque.user.balance
        )

    else:
        flask.flash(_("Ångrade %(text)s-streque på %(name)s.",
                      text=streque.text,
                      name=streque.user.full_name),
                    'success')
        return flask.redirect(flask.url_for('strequelistan.history'))


@mod.route('/notifications')
def notifications():
    notifications = (
        models.Notification
        .query
        .filter_by(
            user_id=current_user.id,
            is_acknowledged=False
        )
        .order_by(models.Notification.timestamp.desc())
        .all()
    )

    if notifications:
        for notification in notifications:
            notification.is_sent = True
        models.db.session.commit()

    return flask.render_template(
        'notifications.html',
        notifications=notifications
    )


@mod.route('/notifications/mark-read')
def mark_notifications_read():
    # Mark all *sent* notifications as acknowledged.
    notifications = (
        models.Notification
        .query
        .filter_by(
            user_id=current_user.id,
            is_sent=True
        )
        .all()
    )

    if notifications:
        for notification in notifications:
            notification.is_acknowledged = True
        models.db.session.commit()

    return flask.redirect(flask.url_for('strequelistan.index'))


@mod.route('/transfer', methods=['POST'])
def credit_transfer():
    form = forms.CreditTransferForm()

    payer = (models.User
             .query
             .filter_by(id=form.payer_id.data)
             .first()
             )

    payee = (models.User
             .query
             .filter_by(id=form.payee_id.data)
             .first()
             )

    if not (payer and payee):
        flask.abort(400)

    redir = flask.redirect(
        flask.url_for('strequelistan.show_profile', user_id=payee.id)
    )

    if form.validate_on_submit():
        if payer != current_user:
            flask.flash(
                _l("Du kan bara föra över pengar från dig själv! >:("),
                'error'
            )
            return redir

        value = int(form.value.data * 100)  # To ören

        message = form.message.data.strip()
        if not message:
            message = None

flasquelistan/templates/change_email_or_password.html
{% extends "layout.html" %}

{% set active_page = "streque" %}

{% from "macros.html" import form_entry %}

{% block body %}
<div class="profile">
  <div>
    <h2>
      {{ user.first_name }}
      {% if user.nickname %}"{{ user.nickname }}"{% endif %}
      {{ user.last_name }}
    </h2>

    <form method="POST">
      {{ form.csrf_token }}

      {{ form_entry(form.email) }}
      {{ form_entry(form.new_password) }}
      {% if current_user.is_admin and current_user.id != user.id and not user.is_admin %}
      <input id="password" name="password" type="hidden" value="not used, Admin is logged in">
      {% else %}
      {{ form_entry(form.password) }}
      {% endif %}
      <div class="form-field">
        <button>Spara</button> | <a href="{{ url_for('strequelistan.edit_profile', user_id=user.id) }}">Avbryt</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

flasquelistan/templates/discord.html
{% extends 'layout.html' %}

{% block scripts %}
<script defer src="{{ url_for("static", filename="js/confirmDialog.js") }}"></script>
{% endblock %}

{% block body %}
<div class="discord-info">
  <h1>{{ _("Streque + Discord = ❤️") }}</h1>
  {% if not user.group.discord_role_id %}
    {{ _('Endast aktiva och före detta korister kan gå med i körens Discord-server. Uppfyller du
          kravet, men ser ändå detta meddelande? Kontakta i så fall') }} <a href="mailto:{{ admin_email }}">
          webmaster</a>.
  {% else %}
  <p>
    {{
      _("Kören har en Discord-server som är integrerad med Strequelistan. För att gå med i servern
         behöver du koppla ditt Discord-konto till ditt Streque-konto, vilket du gör med hjälp av
         länken nedan. Har du inget konto ännu så kan du skapa ett nytt genom samma länk.")
    }}
  </p>
  {% if user.discord_user_id %}
  <p>
    {{ _("Du har redan ett Discord-konto kopplat till Streque:") }}
    <a href="https://discord.com/users/{{ user.discord_user_id }}">{{ user.discord_username }}</a>.
    {{ _("Du kan välja att ta bort ditt Discord-konto från Streque eller att logga in med ett annat
    konto för att byta till det. Notera att du kommer tappa tillgången till körens Discord-server
    om du tar bort kopplingen till ditt Streque-konto.") }}
  </p>
  {% endif %}
  <p>
    <a href="{{ url_for('strequelistan.discord_redirect') }}">
      <img class="discord-logo" src="/static/images/discord.png" />
      {{ _("Logga in med Discord") }}
    </a>
  </p>
  {% if user.discord_user_id %}
  <form method="POST">
  {{ form.csrf_token }}
  <div class="form-entry">
    <button
        class="confirm"
        formaction="{{ url_for('strequelistan.discord_disconnect') }}">
        {{ _("Ta bort mitt Discord-konto från Streque") }}
    </button>
  </div>
  </form>
  {% endif %}

  <h2>{{ _("Frågor och svar") }}</h2>
  <h3>{{ _("Det fungerar inte, vad ska jag ta mig till?") }}</h3>
  <p>
     {{ _('Kontakta') }} <a href="mailto:{{ admin_email }}">webmaster</a> {{ _('via valfritt kommunikationsmedel,
     så får du hjälp!') }}
  </p>
  {% if user.discord_user_id %}
  <h3>{{ _("Min Streque-profil har fel Discord-användarnamn, vad ska jag göra?") }}</h3>
  <p>
    {{ _('Om du har bytt användarnamn på Discord sedan du kopplade ditt konto till Streque så
    uppdateras det inte automatiskt här. Om du vill lösa detta, klicka på "Logga in med Discord"
    ovan och gör om kopplingsprocessen på nytt.') }}
  </p>
  <p>
    {{ _("OBS: notera att det användarnamn som visas här är det du valde när du skapade ditt
    konto, dvs inte samma som ditt smeknamn på servern.") }}
  </p>
  {% endif %}
  {% endif %}
</div>
{% endblock %}

flasquelistan/templates/flashes.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<ul class="flashes">
  {% for category, message in messages %}
  <li class="flash {{ category }}">{{ message|safe }}</li>
  {% endfor %}
</ul>
{% endif %}
{% endwith %}

flasquelistan/templates/layout.html
{% extends "base.html" %}

{% block nav %}
<nav class="bottom-nav">
  <ul>
    <li{% if active_page == 'streque'%} class="active"{% endif %}>
      <a href="{{ url_for('strequelistan.index') }}">
        <!--
          Font Awesome Free 5.3.1 by @fontawesome - https://fontawesome.com
          License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
        -->
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M368 96h-48V56c0-13.255-10.745-24-24-24H24C10.745 32 0 42.745 0 56v400c0 13.255 10.745 24 24 24h272c13.255 0 24-10.745 24-24v-42.11l80.606-35.977C429.396 365.063 448 336.388 448 304.86V176c0-44.112-35.888-80-80-80zm16 208.86a16.018 16.018 0 0 1-9.479 14.611L320 343.805V160h48c8.822 0 16 7.178 16 16v128.86zM208 384c-8.836 0-16-7.164-16-16V144c0-8.836 7.164-16 16-16s16 7.164 16 16v224c0 8.836-7.164 16-16 16zm-96 0c-8.836 0-16-7.164-16-16V144c0-8.836 7.164-16 16-16s16 7.164 16 16v224c0 8.836-7.164 16-16 16z"/></svg>
        {{ _("Streque") }}
      </a>
    </li>
    <li{% if active_page == 'history'%} class="active"{% endif %}>
      <a href="{{ url_for('strequelistan.history') }}">
        <!--
          Font Awesome Free 5.3.1 by @fontawesome - https://fontawesome.com
          License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
        -->
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M504 255.531c.253 136.64-111.18 248.372-247.82 248.468-59.015.042-113.223-20.53-155.822-54.911-11.077-8.94-11.905-25.541-1.839-35.607l11.267-11.267c8.609-8.609 22.353-9.551 31.891-1.984C173.062 425.135 212.781 440 256 440c101.705 0 184-82.311 184-184 0-101.705-82.311-184-184-184-48.814 0-93.149 18.969-126.068 49.932l50.754 50.754c10.08 10.08 2.941 27.314-11.313 27.314H24c-8.837 0-16-7.163-16-16V38.627c0-14.254 17.234-21.393 27.314-11.314l49.372 49.372C129.209 34.136 189.552 8 256 8c136.81 0 247.747 110.78 248 247.531zm-180.912 78.784l9.823-12.63c8.138-10.463 6.253-25.542-4.21-33.679L288 256.349V152c0-13.255-10.745-24-24-24h-16c-13.255 0-24 10.745-24 24v135.651l65.409 50.874c10.463 8.137 25.541 6.253 33.679-4.21z"/></svg>
        {{ _("Historik") }}
      </a>
    </li>
    <li{% if active_page == 'quotes'%} class="active"{% endif %}>
      <a href="{{ url_for('quotes.index') }}">
        <!--
          Font Awesome Free 5.3.1 by @fontawesome - https://fontawesome.com
          License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
        -->
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M464 32H336c-26.5 0-48 21.5-48 48v128c0 26.5 21.5 48 48 48h80v64c0 35.3-28.7 64-64 64h-8c-13.3 0-24 10.7-24 24v48c0 13.3 10.7 24 24 24h8c88.4 0 160-71.6 160-160V80c0-26.5-21.5-48-48-48zm-288 0H48C21.5 32 0 53.5 0 80v128c0 26.5 21.5 48 48 48h80v64c0 35.3-28.7 64-64 64h-8c-13.3 0-24 10.7-24 24v48c0 13.3 10.7 24 24 24h8c88.4 0 160-71.6 160-160V80c0-26.5-21.5-48-48-48z"/></svg>
        {{ _("Citat") }}
      </a>
    </li>
    <li{% if active_page == 'gallery'%} class="active"{% endif %}>
      <a href="{{ url_for('strequelistan.gallery') }}">
        <!--
          Font Awesome Free 5.3.1 by @fontawesome - https://fontawesome.com
          License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
        -->
        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="images" class="svg-inline--fa fa-images fa-w-18" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="currentColor" d="M480 416v16c0 26.51-21.49 48-48 48H48c-26.51 0-48-21.49-48-48V176c0-26.51 21.49-48 48-48h16v208c0 44.112 35.888 80 80 80h336zm96-80V80c0-26.51-21.49-48-48-48H144c-26.51 0-48 21.49-48 48v256c0 26.51 21.49 48 48 48h384c26.51 0 48-21.49 48-48zM256 128c0 26.51-21.49 48-48 48s-48-21.49-48-48 21.49-48 48-48 48 21.49 48 48zm-96 144l55.515-55.515c4.686-4.686 12.284-4.686 16.971 0L272 256l135.515-135.515c4.686-4.686 12.284-4.686 16.971 0L512 208v112H160v-48z"></path></svg>{{ _("Galleri") }}
      </a>
    </li>
  </ul>
</nav>
{% endblock %}

{% block base_body %}
<main{% if main_class %} class="{{ main_class }}"{% endif %}>
  {% include "flashes.html" %}
  {% block body %}
  {% endblock %}
</main>
{% endblock %}

flasquelistan/templates/quote.html
{% extends "layout.html" %}

{% set active_page = "quotes" %}

{% from "quotes.html" import quote_card %}

{% block body %}
<div class="cards">
  <h2>{{ _("Citat") }}</h2>
  {{ quote_card(quote) }}
  <p><a href="{{ url_for('quotes.index') }}">{{ _("Alla citat") }}</a></p>
</div>
{% endblock %}

flasquelistan/templates/strequelistan.html
{% extends "layout.html" %}

{% set active_page = "streque" %}

{% from "quotes.html" import quote_inner %}
{% from "macros.html" import profile_picture %}

{# these will be used many times, call only once #}
{% set add_streque_endpoint = url_for('strequelistan.add_streque') %}
{% set csrf_token = csrf_token() %}  {# seems to be quite slow despite token being cached #}

{% macro usercard(user, articles) %}
<div id="usercard-{{ user.id }}" class="card usercard{% if user in birthdays %} birthday-party{% endif %}">
  <div class="picture-and-name">
    <a href="{{ url_for('strequelistan.show_profile', user_id=user.id) }}">
      {{ profile_picture(user, lazy=True) }}
      <div class="username" data-firstname="{{ user.first_name }}"
                            data-lastname="{{ user.last_name }}"
                            data-nickname="{{ user.nickname or '' }}"
                            data-phonenumber="{{ user.formatted_phone(e164=True) }}">
        {{ user.displayname }}
      </div>
    </a>
    {% if user in users_with_streques %}
    {% set bac = user.bac %}
    {% if bac >= 0.1 %}
    <div class="alcometer">
      {{ user.bac_emoji }}
      <span class="bac">
        {{ '{:.2f}'.format(bac) }}
      </span>
    </div>
    {% endif %}
    {% endif %}
  </div>
  <div class="streque-buttons">
    {% for article in articles %}
    <form class="streque-form" method="POST" action="{{ add_streque_endpoint }}">
      <input type="hidden" name="csrf_token" value="{{ csrf_token }}"/>
      <input type="hidden" name="user_id" value="{{ user.id }}">
      <input type="hidden" name="article_id" value="{{ article.id }}">
      <button class="streque-button"
              type="submit"
              data-userid="{{ user.id }}"
              data-articleid="{{ article.id }}">
        {{ article.name }}
      </button>
    </form>
    {% endfor %}
  </div>
</div>
{% endmacro %}

{% block head %}
<script defer src="{{ url_for('static', filename='js/common.js') }}"></script>
<script defer src="{{ url_for('static', filename='js/streque.js') }}"></script>
<script defer src="{{ url_for('static', filename='js/userFilter.js') }}"></script>
<script defer src="{{ url_for('static', filename='js/lib/confetti.browser.min.js') }}"></script>
{% endblock %}

{% block body %}
<div class="streque-top">
  <nav class="streque-nav">
    <ul>
      <li><a href="{{ url_for("songbook.index") }}" target="_blank" rel="noopener noreferrer">📘 {{ _("Flerstämt") }}</a></li>
      <li><a href="{{ url_for("strequelistan.article_description") }}">💰 {{ _("Prislista") }}</a></li>
      {% if current_user.is_admin %}
      <li><a href="{{ url_for("strequeadmin.index") }}">😎 Admin</a></li>
      {% endif %}
      <li>
        {% if locale().language == 'sv' %}
        <a class="lang-switch inline-icon" href="?lang=en">
          <img src="{{ url_for('static', filename='images/lang_icon.png') }}">English
        </a>
        {% else %}
        <a class="lang-switch inline-icon" href="?lang=sv_SE">
          <img src="{{ url_for('static', filename='images/lang_icon.png') }}">Svenska
        </a>
        {% endif %}
      </li>
      <li><a href="{{ url_for("auth.logout") }}">👋 {{ _("Logga ut") }}</a></li>
    </ul>
  </nav>

  {% set active_birthdays = birthdays|is_active %}
  {% if active_birthdays %}
  <div class="birthdays">
    <p>{{ birthday_emoji }}
      {% if active_birthdays|length > 1 %}
        {% for birthday in active_birthdays %}{# comment to remove whitespace
        #}{% if loop.first %}{% elif loop.last %} {{ _("och") }} {% else %}, {% endif %}
        <a href="#usercard-{{ birthday.id }}">{{ birthday.nickname or birthday.full_name }}</a>{#
        #}{% endfor %}
      {% else %}
        <a href="#usercard-{{ active_birthdays[0].id }}">{{ active_birthdays[0].nickname or active_birthdays[0].full_name }}</a>
      {% endif %}
      {{ _("fyller år idag!!!") }} {{ birthday_emoji }}
    </p>
  </div>
  {% endif %}

  {% if quote %}
    <blockquote class="quote quote-display">
      {{ quote_inner(quote) }}
    </blockquote>
  {% endif %}

</div>

<div class="cards">
  <input id="ajax-csrf_token" type="hidden" name="csrf_token" value="{{ csrf_token }}"/>

  <h2>{{ _("Inloggad användare") }}</h2>
  {% if notification_count %}
  <p>
    <a href="{{ url_for('strequelistan.notifications') }}">
      {{ _("Du har %(num)d notifikation(er)!", num=notification_count) }}
    </a>
  </p>
  {% endif %}
  {% if has_pending_nicknames %}
  <p>
    <a href="{{ url_for('strequeadmin.show_nicknames') }}">
      {{ _("Det finns nya smeknamnsförslag!") }}
    </a>
  </p>
  {% endif %}
  {{ usercard(current_user, articles) }}

  <h2 class="jump-to-group">{{ _("Hoppa till") }}</h2>
  {% for group in groups %}
  <a class="jump-to-group" href="#group-{{ group.id }}">{{ group.name }}</a>
  {% if not loop.last %} - {% endif %}
  {% endfor %}

  <h2 class="user-filter">{{ _("Filtrera användare") }}</h2>
  <div class="user-filter">
      <p><small>{{ _("Du kan söka på namn, smeknamn och telefonnummer.") }}</small></p>
    <input type="text" id="user-filter" placeholder="Namn" autocomplete="off">
    <button id="clear-filter" type="button">{{ _("Rensa") }}</button>
  </div>

  {% if vip %}
  <div id="group-vip" class="group">
    <h2>VIP</h2>
    {% for user in vip %}
    {{ usercard(user, articles) }}
    {% endfor %}
  </div>
  {% endif %}

  {% for group in groups %}
  <div id="group-{{ group.id }}" class="group">
    <h2>{{ group.name }}</h2>
    <a href="#">{{ _("Gå till toppen") }}</a>
    {% for user in group.users %}
    {{ usercard(user, articles) }}
    {% endfor %}
  </div>
  {% endfor %}
</div>

<div id="stupid-buttons">
  <p class="no-js">Activate JavaScript to use the stupid buttons</p>
</div>
{% endblock %}

flasquelistan/templates/transfer_standalone.html
{% extends "layout.html" %}

{% set active_page = "streque" %}
{% set main_class = "non-padded" %}

{% from "macros.html" import form_entry %}

{% block body %}
<div class="profile">
  <div class="profile-content">
    <form id="transfer" method="POST" action="{{ url_for('strequelistan.credit_transfer') }}">
      {{ credit_transfer_form.csrf_token }}
      {{ credit_transfer_form.payer_id }}
      {{ credit_transfer_form.payee_id }}
      <fieldset>
        <legend>{{ _("Streque Pay") }}</legend>
        <div class="form-entry">
          {{ _("Från") }}: {{ current_user.full_name }}<br/>
          {{ _("Till") }}: {{ user.full_name }}
        </div>
        {{ form_entry(credit_transfer_form.value) }}
        {{ form_entry(credit_transfer_form.message) }}
        {% if user.id == current_user.id %}
            <button disabled>{{ _("(du kan inte Streque Pay:a dig själv)") }}</button>
        {% else %}
            <button>{{ _("Skicka") }}</button>
        {% endif %}
      </fieldset>
    </form>
  </div>
</div>
<a href="{{ url_for('strequelistan.show_profile', user_id=user.id) }}">{{ _("Gå till profil") }}</a>
{% endblock %}